parameters:
    pim_direct_to_mongodb.normalizer.mongodb.reference_data.class: Pim\Bundle\DirectToMongoDBBundle\Normalizer\ReferenceDataNormalizer

services:
    pim_direct_to_mongodb.normalizer.mongodb.reference_data:
        class: %pim_direct_to_mongodb.normalizer.mongodb.reference_data.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }
